    var BuzzwordText = {
	"0": "Freakshow Freifeld, immer aktiv",
	"1": "App net oder App dot net wird ausgesprochen",
	"2": "Spiele / Games als Thema oder Spruch",
	"3": "Bitcoin, exakter ausspruch",
	"4": "Scharfe Atemgeraeusche, genannt vadern sind hoerbar",
	"5": "Google ist Thema oder wird ausgesprochen",
	"6": "shut up and take my money meme wird genutzt",
	"7": "Bumm Zack Return oder Bumm Zack oder Zack Return",
	"8": "Flash nur in bezug auf das adobe flash framework",
	"9": "Flattr ist Thema oder wird als Begriff ausgesprochen",
	"10": "Die Deutsche Telekom oder T-online sind Thema oder werden als Begriff ausgesprochen",
	"11": "IPv6 ist Thema oder wird als Begriff ausgesprochen",
	"12": "Podcast ist Thema oder wird als Begriff ausgesprochen",
	"13": "Das OS Windows ist Thema oder fällt als Begriff",
	"14": "Mac Pro oder MacBook Pro sind Thema oder werden als Begriff ausgesprochen",
	"15": "Der Kalender Rant wird thematisiert oder referenziert",
	"16": "skip skip skip als signal das thema zu wechseln",
	"17": "Das Filesystem ZFS oder openZFS wird thematisiert oder referenziert",
	"18": "Steve als referenz zu Steve Jobs wird ausgesprochen",
	"19": "Womit wir das schon mal geklärt hätten exakt ausgesprochen",
	"20": "KliX0r oder HaX0r werden ausgesprochen",
	"21": "Eine Firma, Person oder Konzept wird als teuflisch oder evil bezeichnet",
	"22": "Nokia oder deren Absturz werden erwaehnt",
	"23": "Der Chaos Communication Congress oder das Camp werden erwaehnt",
	"24": "droelfzig, zweiendroelfzig wird erwaehnt nicht unbedingt von clemens",
	"25": "encrypt oder verschluesseln wird in jeglicher grammatik ausgesprochen",
	"26": "Schwelgen in historischen geschehnissen oder direkt ausgesprochen",
	"27": "Kapitelmarke in jeglicher grammatikalischen form werden ausgesprochen",
	"28": "Der Chat wird erwaehnt",
	"29": "exakte erwähnung als ausspruch",
	"30": "peak... in bezug auf den niedergang eins einst relevanten players",
	"31": "Die Programmiersprache erlang wird erwähnt",
	"32": "Der original Freakshow Trinkspiel spruch fällt. PROOOOOST!",
	"33": "Tesla wird in jeglichem kontext erwähnt",
	"34": "Jemand holt Bier, es wird Bier erwähnt oder es klimpern bierflaschen",
	"35": "Jeder arsch und sein bruder, meist von denisx, muss aber nicht",
	"36": "FAIL wird exakt erwähnt",
	"37": "Es wird mit DEUTLICH angestengter Stimme granted!",
	"38": "...dran lecken wird im context und grammatikalisch frei erwähnt  ",
	"39": "mit soße und scharf, meist von clemens, muss aber nicht",
	"40": "...rechts unten, wählt die maximale qualitäts und ausbaustufe ohne auf den Preis zu achten ",
	"41": "Apple Store wird exakt erwähnt, nicht App Store",
	"42": "Unnoetige und gehäufte verwendung von anglizismen",
	"43": "blankes oder nacktes metall wird erwähnt",
	"44": "das meme 'what could possibly go wrong' wird frei zitiert",
	"45": "Der Flughafen BER fail wird erwähnt",
	"46": "Hall, Echo, Knistern, Latenz oder sonstige auffällig Sound Setup probleme",
	"47": "die metaebene wir erwähnt",
	"48": "Schnuppsi, ein kleines fragiles suesses etwas",
	"49": "Wir sollten oder muessten mal mehr ueber macs reden, wird ausgesprochen ",
	"50": "Die Räuspertaste wurde deutlich hoerbar vergessen",
	"51": "Taatsächlich, meist von hukl gesagt, muss aber nicht",
	"52": "louis de funes 'nein... doch... ohhh!' wird exakt ausgesprochen",
	"53": "Alle so YEAH, meist von denis oder clemens, muss aber nicht",
	"54": "Klickibunti exakt erwähnt",
	"55": "Die Fritzbox oder die Firma AVM sind Thema oder werden erwähnt",
	"56": "Das mobil OS Android wird explizit erwähnt",
	"57": "otto normal facetuber wird erwähnt",
	"58": "Die shownotes werden exakt erwähnt",
	"59": "Haben wir noch Themen oder ähnlich z.B. so wenig Themen heute",
	"60": "Schlumpfbeeren als sinnbild für unsinnige Punktesammelei und quantifizierung werden erwähnt",
	"61": "Linux oder GNU werden erwähnt",
	"62": "Ein versuchter witz war flach wie eine flunder und verursacht kurz schweigen in der Runde",
	"63": "Cloud oder die Wolke wird erwähnt",
	"64": "Jede form von essen während der sendung oder als thema",
	"65": "Hipster oder nerds werden erwähnt",
	"66": "jeglich art von illegalen drogen wird erwähnt oder ausprobiert",
	"67": "Lulu referenz im sinne von das stinkt in jeglicher form",
	"68": "Die allwissende müllhalde oder wikipedia werden erwähnt",
	"69": "Stimme der Jugend, meist als beschreibung für hukl, muss aber nicht",
	"70": "Apple politik oder produkt wird verklärt oder schoen geredet",
	"71": "und ueberhaupt wird exakt erwähnt",
	"72": "Open Source, quelloffen oder freie software werden erwähnt",
	"73": "die chinesen werden in jeglichem kntext erwähnt",
	"74": "Fefe oder verschwoerungs theorien werden erwähnt",
	"75": "'Wir prangern das an' oder grammatikalisch ähnlich",
	"76": "freebsd wir exakt erwähnt",
	"77": "glasfaser wird gefordert oder sonst wie erwähnt",
	"78": "kleinkuhkackerode wird exakt erwähnt",
	"79": "'Wir fordern zukunft', 'in zukunft' oder ähnlich",
	"80": "das wort fnord fällt oder ein fnord wird besprochen",
	"81": "",
	"82": ""	
      }
  